import { createThemeContract } from '@vanilla-extract/css'

export const themeVars = createThemeContract({
  color: {
    backgroundColor: null,
    blue10: null,
    blue20: null,
    blue30: null,
    blue40: null,
    blue50: null,
    blue60: null,
    blue70: null,
    blue80: null,
    blue90: null,
    blue100: null,
    gray10: null,
    gray20: null,
    gray30: null,
    gray40: null,
    gray50: null,
    gray60: null,
    gray70: null,
    gray80: null,
    gray90: null,
    gray100: null,
    green10: null,
    green20: null,
    green30: null,
    green40: null,
    green50: null,
    green60: null,
    green70: null,
    green80: null,
    green90: null,
    green100: null,
    highlightHover: null,
    highlightPressed: null,
    purple10: null,
    purple20: null,
    purple30: null,
    purple40: null,
    purple50: null,
    purple60: null,
    red10: null,
    red20: null,
    red30: null,
    red40: null,
    red50: null,
    red60: null,
    red70: null,
    red80: null,
    red90: null,
    red100: null
  }
})
